defmodule Creative.Repo.Migrations.CreateContacts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :first_name, :citext, null: false
      add :last_name, :citext
      add :birth_date, :date
      add :phone, :text
      add :email, :citext

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:contacts, ["email"], name: "contacts_email_index")

    create unique_index(:contacts, ["first_name", "last_name"],
             name: "contacts_full_name_index",
             nulls_distinct: false
           )

    create unique_index(:contacts, ["phone"], name: "contacts_phone_index")
  end

  def down do
    drop_if_exists unique_index(:contacts, ["phone"], name: "contacts_phone_index")

    drop_if_exists unique_index(:contacts, ["first_name", "last_name"],
                     name: "contacts_full_name_index"
                   )

    drop_if_exists unique_index(:contacts, ["email"], name: "contacts_email_index")

    drop table(:contacts)
  end
end
